// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220926200309_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.RatesUpdate", b =>
                {
                    b.Property<int>("IdRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rate");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRate"), 1L, 1);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("currency");

                    b.Property<int>("IdUpdate")
                        .HasColumnType("int")
                        .HasColumnName("id_update");

                    b.HasKey("IdRate");

                    b.HasIndex("IdUpdate");

                    b.ToTable("Rates_Update", (string)null);
                });

            modelBuilder.Entity("Entities.Update", b =>
                {
                    b.Property<int>("IdUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_update");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUpdate"), 1L, 1);

                    b.Property<string>("Base")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("base");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("date_update");

                    b.Property<string>("Timestamp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("timestamp");

                    b.HasKey("IdUpdate");

                    b.ToTable("Update", (string)null);
                });

            modelBuilder.Entity("Entities.RatesUpdate", b =>
                {
                    b.HasOne("Entities.Update", "IdUpdateNavigation")
                        .WithMany("RatesUpdates")
                        .HasForeignKey("IdUpdate")
                        .IsRequired()
                        .HasConstraintName("FK_Rates_Update_Update");

                    b.Navigation("IdUpdateNavigation");
                });

            modelBuilder.Entity("Entities.Update", b =>
                {
                    b.Navigation("RatesUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
